<?php

namespace App\Filament\Resources\DestinationResource\RelationManagers;

use App\Models\Hotel;
use Filament\Forms;
use Filament\Forms\Components\Select;
use Filament\Forms\Form;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables;
use Filament\Tables\Table;

class HotelsRelationManager extends RelationManager
{
    protected static string $relationship = 'hotels';

    public function getInverseRelationshipName(): ?string
    {
        return 'destination'; // TODO: Change the autogenerated stub
    }

    public function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('name')
                    ->required()
                    ->maxLength(255),
            ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->recordTitleAttribute('name')
            ->columns([
                Tables\Columns\TextColumn::make('name'),
                Tables\Columns\TextColumn::make('address'),
                Tables\Columns\TextColumn::make('city'),
                Tables\Columns\TextColumn::make('country'),
                Tables\Columns\TextColumn::make('phone'),
            ])
            ->filters([
                //
            ])
            ->headerActions([
                Tables\Actions\AssociateAction::make()
                    ->recordSelect(
                        function (Select $select) {
                            return $select->searchable()
                                ->getSearchResultsUsing(fn (string $search): array => Hotel::where('name', 'like', "%{$search}%")
                                    ->orWhere('address', 'like', "%{$search}%")
                                    ->limit(5)
                                    ->get(['name', 'address', 'id'])
                                    ->mapWithKeys(fn ($hotel) => [$hotel->id => $hotel->name.' - '.$hotel->address])
                                    ->toArray())
                                ->getOptionLabelUsing(function ($value): ?string {
                                    $hotel = Hotel::find($value);

                                    return $hotel ? $hotel->name.' - '.$hotel->address : null;
                                });
                        }
                    ),
            ])
            ->actions([
                Tables\Actions\EditAction::make()
                    ->url(fn (Hotel $hotel) => url("/admin/hotels/{$hotel->id}/edit")),
                Tables\Actions\DissociateAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ])
            ->emptyStateActions([
                Tables\Actions\AssociateAction::make()
                    ->recordSelect(
                        function (Select $select) {
                            return $select->searchable()
                                ->getSearchResultsUsing(fn (string $search): array => Hotel::where('name', 'like', "%{$search}%")
                                    ->orWhere('address', 'like', "%{$search}%")
                                    ->limit(5)
                                    ->get(['name', 'address', 'id'])
                                    ->mapWithKeys(fn ($hotel) => [$hotel->id => $hotel->name.' - '.$hotel->address])
                                    ->toArray())
                                ->getOptionLabelUsing(function ($value): ?string {
                                    $hotel = Hotel::find($value);

                                    return $hotel ? $hotel->name.' - '.$hotel->address : null;
                                });
                        }
                    ),
            ]);
    }
}
