<?php

namespace App\Filament\Resources\OriginResource\RelationManagers;

use App\Models\Airport;
use Filament\Actions\AssociateAction;
use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\DissociateAction;
use Filament\Forms\Components\Select;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Schemas\Schema;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class AirportsRelationManager extends RelationManager
{
    protected static string $relationship = 'airports';

    public function getInverseRelationshipName(): ?string
    {
        return 'origin'; // TODO: Change the autogenerated stub
    }

    public function form(Schema $schema): Schema
    {
        return $schema
            ->components([
                Select::make('origin_id')
                    ->placeholder('Select an airport')
                    ->options(
                        Airport::all()->pluck('codeIataAirport', 'id')
                    )
                    ->label('Airport')
                    ->relationship('airport', 'codeIataAirport')
                    ->required()
                    ->searchable(),
            ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->recordTitleAttribute('codeIataAirport')
            ->columns([
                TextColumn::make('codeIataAirport')
                    ->label('IATA Code'),
                TextColumn::make('nameAirport')
                    ->label('Name'),
            ])
            ->filters([
                //
            ])
            ->headerActions([
                AssociateAction::make(),
            ])
            ->recordActions([
                DissociateAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ])
            ->emptyStateActions([
                AssociateAction::make()
                    ->recordTitleAttribute('codeIataAirport'),
            ]);
    }
}
