<?php

namespace App\Filament\Resources\OriginResource\RelationManagers;

use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables;
use Filament\Tables\Table;

class AirportsRelationManager extends RelationManager
{
    protected static string $relationship = 'airports';

    public function getInverseRelationshipName(): ?string
    {
        return 'origin'; // TODO: Change the autogenerated stub
    }

    public function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Select::make('origin_id')
                    ->placeholder('Select an airport')
                    ->options(
                        \App\Models\Airport::all()->pluck('codeIataAirport', 'id')
                    )
                    ->label('Airport')
                    ->relationship('airport', 'codeIataAirport')
                    ->required()
                    ->searchable(),
            ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->recordTitleAttribute('codeIataAirport')
            ->columns([
                Tables\Columns\TextColumn::make('codeIataAirport')
                    ->label('IATA Code'),
                Tables\Columns\TextColumn::make('nameAirport')
                    ->label('Name'),
            ])
            ->filters([
                //
            ])
            ->headerActions([
                Tables\Actions\AssociateAction::make(),
            ])
            ->actions([
                Tables\Actions\DissociateAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ])
            ->emptyStateActions([
                Tables\Actions\AssociateAction::make()
                    ->recordTitleAttribute('codeIataAirport'),
            ]);
    }
}
